version: '3.9'
services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    user: root
    privileged: true
    environment:
      TZ: "Asia/Seoul"
      JAVA_OPTS: "-Dhudson.model.DownloadService.noSignatureCheck=true"
    ports:
      - "80:8080"
    volumes:
      - "./jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
